# 步骤 4: 动态发现、下载、重命名并放置文件
      # 关键：此步骤只有在 needs_sync=true 时才会运行
      - name: Discover, Download, Rename, and Place Files
        if: steps.check_for_updates.outputs.needs_sync == 'true'
        env:
          GH_TOKEN: ${{ secrets.CROSS_REPO_PAT }}
        run: |
          # --- 配置区 ---
          SOURCE_REPO="ZZZure/ZZZeroUID"
          SOURCE_BRANCH="master" 
          # 修正：根据您提供的截图，正确的根目录是 ZZZeroUID (没有连字符)
          BASE_PATH="ZZZeroUID"
          DEST_DIR="resources/enka"
          API_URL="https://api.github.com/repos/$SOURCE_REPO/contents"
          # --- 配置区结束 ---

          echo "准备将文件同步到 $DEST_DIR 目录..."
          mkdir -p $DEST_DIR

          # 1. 处理没有版本号的静态文件
          echo "--- 处理静态文件 ---"
          # 修正：在路径前加上正确的 $BASE_PATH
          static_files=(
            "$BASE_PATH/utils/alias/char_alias.json"
            "$BASE_PATH/utils/map/PartnerScore.json"
          )
          for file_path in "${static_files[@]}"; do
            filename=$(basename "$file_path")
            echo "处理: $filename"
            source_url="https://raw.githubusercontent.com/$SOURCE_REPO/$SOURCE_BRANCH/$file_path"
            dest_file="$DEST_DIR/$filename"
            curl -s -L -f -o "$dest_file" "$source_url"
          done

          # 2. 处理带有动态版本号的文件
          echo "--- 处理动态版本号文件 ---"
          # 修正：API请求的路径也需要加上正确的 $BASE_PATH
          MAP_DIR_PATH="$BASE_PATH/utils/map"
          echo "正在从 API 获取 $SOURCE_REPO/$MAP_DIR_PATH 的文件列表..."
          map_files_json=$(curl -s -f -L -H "Authorization: Bearer $GH_TOKEN" "$API_URL/$MAP_DIR_PATH?ref=$SOURCE_BRANCH")
          
          if ! echo "$map_files_json" | jq -e . > /dev/null 2>&1; then
            echo "::error::无法从 GitHub API 获取文件列表或返回格式错误。"
            echo "API 响应: $map_files_json"
            exit 1
          fi

          dynamic_file_prefixes=( "EquipId2Data" "PartnerId2Data" "PartnerId2SkillParam" "WeaponId2Data" )
          for prefix in "${dynamic_file_prefixes[@]}"; do
            full_filename=$(echo "$map_files_json" | jq -r ".[] | select(.name | startswith(\"$prefix\") and endswith(\".json\")) | .name" | head -n 1)

            if [[ -n "$full_filename" ]]; then
              # 修正：构建文件路径时使用正确的 MAP_DIR_PATH
              file_path="$MAP_DIR_PATH/$full_filename"
              new_filename="$prefix.json"
              source_url="https://raw.githubusercontent.com/$SOURCE_REPO/$SOURCE_BRANCH/$file_path"
              dest_file="$DEST_DIR/$new_filename"
              
              echo "发现动态文件: $full_filename"
              echo "  -> 重命名为: $new_filename"
              echo "  -> 保存至: $dest_file"
              curl -s -L -f -o "$dest_file" "$source_url"
            else
              echo "::warning:: 未在源仓库中找到任何以 '$prefix' 开头的文件。"
            fi
          done

          echo "所有文件处理完毕。"
